# Generated by Django 3.0.7 on 2020-06-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passagens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passagem',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
