# Generated by Django 3.0.7 on 2020-06-28 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passagens', '0002_passagem_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passagem',
            name='email',
        ),
    ]
